CREATE DATABASE BDAutomotivo;
GO
USE BDAutomotivo;

CREATE TABLE TBFabricante(
ID INT IDENTITY,
NOME VARCHAR(50) NOT NULL,
CONSTRAINT PK_TBFabricante_ID PRIMARY KEY(ID)
);

CREATE TABLE TBVeiculo(
ID INT IDENTITY,
MODELO VARCHAR(30) NOT NULL,
PLACA CHAR(7) NOT NULL,
ID_FABRICANTE INT NOT NULL,
CONSTRAINT PK_TBVeiculo_ID PRIMARY KEY(ID),
CONSTRAINT FK_TBVeiculo_TBFabricante
	FOREIGN KEY(ID_FABRICANTE)
	REFERENCES TBFabricantes(ID)
);